all:
  children:
    vpn_exit:
      hosts:
        erg-tr:
          ansible_host: 82.26.94.37
          server_location: TR
        erg-de:
          ansible_host: 46.224.49.250
          server_location: DE
          server_provider: Hetzner
        erg-fi:
          ansible_host: 109.120.187.205
          server_location: FI
        erg-pl:
          ansible_host: 193.200.16.140
          server_location: PL
          server_provider: BlueVPS
    dpi_bypass:
      hosts:
        erg-ru:
          ansible_host: 192.168.2.92
          server_location: RU-LAN
          server_provider: local-pi5
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
