all:
  children:
    vpn_exit:
      hosts:
        erg-tr:
          ansible_host: 10.12.12.101
          public_host: 82.26.94.37
          mgmt_tunnel_host: 10.12.12.101
          server_location: TR
        erg-de:
          ansible_host: 46.224.49.250
          public_host: 46.224.49.250
          mgmt_tunnel_host: 10.12.12.102
          server_location: DE
          server_provider: Hetzner
        erg-fi:
          ansible_host: 10.12.12.103
          public_host: 109.120.187.205
          mgmt_tunnel_host: 10.12.12.103
          server_location: FI
        erg-pl:
          ansible_host: 10.12.12.100
          public_host: 193.200.16.140
          mgmt_tunnel_host: 10.12.12.100
          ansible_port: 56777
          server_location: PL
          server_provider: BlueVPS
        erg-tr-fast:
          ansible_host: 10.12.12.104
          public_host: 185.229.12.109
          mgmt_tunnel_host: 10.12.12.104
          server_location: TR
          server_provider: vps.com.tr
    dpi_bypass:
      hosts:
        erg-ru:
          ansible_host: 192.168.2.92
          public_host: 192.168.2.92
          server_location: RU-LAN
          server_provider: local-pi5
    proxima_sites:
      hosts:
        svr:
          ansible_host: 10.12.12.10
          public_host: 192.168.2.96
          mgmt_tunnel_host: 10.12.12.10
          ansible_user: root
          server_code: SVR
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
